service:
  name: hazree-backend

package:
  individually: true
  
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    excludeFiles: '**/*.test.ts' #Excluding test files in the final build
  serverless-iam-roles-per-function:
    defaultInherit: true # Each function will inherit the service level roles too.
  prune:
    automatic: true
    number: 3

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-prune-plugin
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  frameworkVersion: ‘1.64.1’
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'} # Deployment to be in london
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    DEBUG: '*'
    ENV: ${self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  tracing:
    apiGateway: false
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"
functions:
  ping:
    handler: src/api/functions/ping-pong/ping-pong.lambda.handler
    events:
      - http:
          method: get
          path: ping
  timesheet-daily:
    handler: src/api/functions/timesheets/timesheet-daily.lambda.handler
    events:
      - http:
          method: get
          path: admin/timesheet/daily/{date}
          