service:
  name: hazree-backend

package:
  individually: true
  
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: 
      forceExclude:
        - aws-sdk
    excludeFiles: '**/*.test.ts' #Excluding test files in the final build
  serverless-iam-roles-per-function:
    defaultInherit: true # Each function will inherit the service level roles too.
  prune:
    automatic: true
    number: 3

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-prune-plugin
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  frameworkVersion: ‘1.64.1’
  stage: ${opt:stage, 'dev'} # default sls deploy will deploy to dev
  region: ${opt:region, 'eu-west-2'} # Deployment to be in london
  memorySize: 128 # Lambda function to take default memory of 128 MB only overwrite in function if you need to update
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  deploymentBucket:
    name: com.serverless.hazree.deploys # Change with the project name
    maxPreviousDeploymentArtifacts: 3
  environment:
    DEBUG: '*'
    ENV: ${self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  role: arn:aws:iam::428694752194:role/cloud9-helloWorld-helloRole-1ES8HB9ZW7VZD

functions:
  ping:
    handler: src/api/functions/ping-pong/ping-pong.handler
    events:
      - http:
          method: get
          path: ping
          cors: true
  timesheet-daily:
    handler: src/api/functions/timesheets/timesheet-daily.handler
    events:
      - http:
          method: get
          path: admin/timesheet/daily/{date}
          cors: true
          